global:
  scrape_interval: '5s'
  scrape_timeout: '10s'
  evaluation_interval: '5s'
  labels:
        monitor: 'maestro'

scrape_configs:
- job_name: 'prometheus'
  target_groups:
  - targets: ['localhost:9090']

- job_name: 'node-exporter'
  target_groups:
  - targets: [
    'core-01.maestro.io:9100',
    'core-02.maestro.io:9100',
    'core-03.maestro.io:9100'
  ]

- job_name: 'cadvisor'
  target_groups:
  - targets: [
    '1.cadvisor.metrics.prod.crisidev.maestro.io:8080',
    '2.cadvisor.metrics.prod.crisidev.maestro.io:8080',
    '3.cadvisor.metrics.prod.crisidev.maestro.io:8080'
  ]

- job_name: 'skydns'
  target_groups:
  - targets: [
    'core-01.maestro.io:3000',
    'core-02.maestro.io:3000',
    'core-03.maestro.io:3000'
  ]
