global:
  scrape_interval: '15s'
  scrape_timeout: '30s'
  evaluation_interval: '15s'
  labels:
        monitor: 'maestro'

scrape_configs:
- job_name: 'prometheus'
  target_groups:
  - targets: ['localhost:9090']

- job_name: 'node-exporter'
  scrape_interval: '5s'
  evaluation_interval: '5s'
  target_groups:
  - targets: [
    'core-01.node-exporter.metrics.prod.crisidev.maestro.io:9100',
    'core-02.node-exporter.metrics.prod.crisidev.maestro.io:9100',
    'core-03.node-exporter.metrics.prod.crisidev.maestro.io:9100'
  ]

- job_name: 'cadvisor'
  scrape_interval: '5s'
  evaluation_interval: '5s'
  target_groups:
    - targets: [
      'cadvisor-core-01.maestro.io:80',
      'cadvisor-core-02.maestro.io:80',
      'cadvisor-core-03.maestro.io:80'
  ]

- job_name: 'skydns'
  target_groups:
  - targets: [
    'core-01.maestro.io:3000',
    'core-02.maestro.io:3000',
    'core-03.maestro.io:3000'
  ]
